basePath: /v2
definitions:
  rootdescription.Address_Struct:
    properties:
      house:
        type: integer
      street:
        type: string
    type: object
  rootdescription.sku_struct:
    properties:
      address_Struct:
        $ref: '#/definitions/rootdescription.Address_Struct'
      sku_email:
        type: string
      id:
        type: string
      sku_name:
        type: string
      sku_type:
        type: string
    type: object
host: 10.1.99.32:8181
info:
  contact:
    name: Dmitry
    url: https://github.com/chernienkoii/Connector_1C_Enterprise
  description: API description
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger API Connector for 1C Enterprise
  version: "1.0"
paths:
  /api_json:
    post:
      consumes:
      - application/json
      description: Get-Set sku
      operationId: Exchange-sku
      parameters:
      - description: id_sku
        in: query
        name: id_sku
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            items:
              $ref: '#/definitions/rootdescription.sku_struct'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Exchange sku
  /list_sku:
    get:
      consumes:
      - application/json
      description: Get all sku
      operationId: Get-all-sku
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            items:
              $ref: '#/definitions/rootdescription.sku_struct'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all sku
swagger: "2.0"
