basePath: /v2
definitions:
  rootdescription.Address_Struct:
    properties:
      house:
        type: integer
      street:
        type: string
    type: object
  rootdescription.Customer_struct:
    properties:
      address_Struct:
        $ref: '#/definitions/rootdescription.Address_Struct'
      customer_email:
        type: string
      customer_id:
        type: string
      customer_name:
        type: string
      customer_type:
        type: string
    type: object
host: localhost:8181
info:
  contact:
    name: Dmitry
    url: https://github.com/chernienkoii/Connector_1C_Enterprise
  description: API description
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger API Connector for 1C Enterprise
  version: "1.0"
paths:
  /api_json:
    post:
      consumes:
      - application/json
      description: Get-Set Customer
      operationId: Exchange-Customer
      parameters:
      - description: id_customer
        in: query
        name: id_customer
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            items:
              $ref: '#/definitions/rootdescription.Customer_struct'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Exchange Customer
  /list_customer:
    get:
      consumes:
      - application/json
      description: Get all Customer
      operationId: Get-all-Customer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            items:
              $ref: '#/definitions/rootdescription.Customer_struct'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all Customer
swagger: "2.0"
